### PR TITLE
adding nav service

### PR DESCRIPTION
**Pull request by jstenhouse**
@holtbp @rantler 

Not sure if there's a better way to do this, but having a `nav` service seems like it would solve the problem of redefining the same navigation functions.

Any controller/view that has an `ng-click` will need to inject the nav service and then add it to the `$scope` like `$scope.nav = nav;`. Maybe there are convenience methods of `$scope` that I'm not aware of?

### CODE REVIEW

**Comment by holtbp** [comment]
This looks good to me. @vicentereig might have input about the standard way of handling this in Angular.

**Comment by vicentereig** [comment]
@jstenhouse This seems to be a good point to start using a routing library. In my experience, https://github.com/dotJEM/angular-routing is the most reliable. Docs aren't great at the moment[1], but I put together a tutorial on Jive in the follow-up for the second ng-workshop (source code at https://github.com/vicentereig/nr-workshop)

Routes are an important piece of the MVC architecture. In other MVC implementations they are known as the Mediating Controller. They basically are responsible for loading data, bootstrapping the necessary objects, and trigger the render loop.

If you want me I can sketch an implementation this evening in this PR.

[1] I'm working on improving it.

**Comment by jstenhouse** [comment]
Thanks @vicentereig - I'll take a look at this tonight.

**Comment by vicentereig** [comment]
BTW I'd remove `turbolinks`, it may create some confusion in the near future!

https://github.com/holtbp/beery/blob/master/Gemfile#L26-L27
https://github.com/holtbp/beery/blob/master/app/assets/javascripts/application.js#L15

**Comment by jstenhouse** [comment]
Removing turbolinks in https://github.com/holtbp/beery/pull/7

**Comment by jstenhouse** [comment]
Closing this PR in favor of the angular-routing or ui-router options.

**Comment by jstenhouse** [comment]
Moving to angular-routing in https://github.com/holtbp/beery/pull/8

**Pull request closed without merging**
